### ISSUE TITLE
Support for retrieving futures commission rates?

### ISSUE THREAD

**Issue by hoeckxer** [LUCIT-Systems-and-Development/unicorn-binance-rest-api#18]
While making use of this excellent library, I was looking to retrieve the user commission rates from the endpoint https://binance-docs.github.io/apidocs/futures/en/#user-commission-rate-user_data. Unfortunately I couldn't find the function in the rest-manager to achieve this. Would it be possible to have support added for this endpoint?

Or if I've overlooked the function, I'd appreciate somebody pointing me to the right place!

Kind regards!

**Comment by oliver-zehentleitner** [comment]
Yes its missing!

It should be easy to add, you want to make a PR?

**Comment by oliver-zehentleitner** [comment]
I dont trade futures and i dont get the permissions to work atm. (error 2015) Can you try please? https://github.com/LUCIT-Systems-and-Development/unicorn-binance-rest-api/blob/master/example_commission_rate.py

**Comment by oliver-zehentleitner** [comment]
Ok, it seems binance needed a while till 2015 error gets removed.

I was able to successfully test the new function:
[example_futures_commission_rate.py](https://github.com/LUCIT-Systems-and-Development/unicorn-binance-rest-api/blob/master/example_futures_commission_rate.py) 
{'symbol': 'BTCUSDT', 'makerCommissionRate': '0.000200', 'takerCommissionRate': '0.000400'}

https://unicorn-binance-rest-api.docs.lucit.tech/unicorn_binance_rest_api.html?highlight=futures_commission_rate#unicorn_binance_rest_api.manager.BinanceRestApiManager.futures_commission_rate

**Comment by oliver-zehentleitner** [comment]
https://github.com/LUCIT-Systems-and-Development/unicorn-binance-rest-api/releases/tag/1.4.0
