### ISSUE TITLE
async Client API Requests

### ISSUE THREAD

**Issue by oliver-zehentleitner** [LUCIT-Systems-and-Development/unicorn-binance-rest-api#49]
### Discussed in https://github.com/LUCIT-Systems-and-Development/unicorn-binance-rest-api/discussions/48

<div type='discussions-op-text'>

<sup>Originally posted by **45by90** September 17, 2022</sup>
Hello,

Is there a way to make async client API calls, i.e., make a trade call and wait for it while still getting in streaming data?

The websocket stream is blocked while trying to make a trade (maybe a couple of tries).  By the time the trade goes through or fails, the stream rushes to catch up and everything gets screwed up.  Or perhaps something I'm missing?  I've tried things like:

  ```
with c.concurrent.futures.ThreadPoolExecutor() as executor:
      future = executor.submit(self._executor,'BUY',quant,trade_this_price,price_filter)
      trade_r = future.result()
```

But it still blocks the main process (for example, I have a window display updating, which freezes while the order executions are trying to get put through).

Thank you,

JJ
</div>

**Comment by 45by90** [comment]
Any thoughts on this?

**Comment by oliver-zehentleitner** [comment]
yes, we want to release an async extension. so that classic and async version will be available together.

**Comment by oliver-zehentleitner** [comment]
Continue here: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-rest-api/issues/15
