### ISSUE TITLE
GET /fapi/v1/account is retired, please use GET /fapi/v2/account

### ISSUE THREAD

**Issue by vunovikov** [LUCIT-Systems-and-Development/unicorn-binance-rest-api#65]
### Version of this library.

unicorn_fy: 0.12.2
unicorn_binance_local_depth_cache: 0.7.3
unicorn_binance_rest_api: 1.10.0
unicorn_binance_trailing_stop_loss: 0.8.0
unicorn_binance_websocket_api: 1.46.1

### Solution to Issue cannot be found in the documentation or other Issues and also occurs in the latest version of this library.

- [X] I checked the documentation and other Issues. I am using the latest version of this library.

### Hardware?

Local server/workstation

### Operating System?

Windows

### Python version?

Python3.10

### Used endpoint?

binance.com-futures

### Issue

I am getting the following error:

unicorn_binance_rest_api.exceptions.BinanceAPIException: APIError(code=-5000): GET /fapi/v1/account is retired, please use GET /fapi/v2/account

Can you tell me how I can fix it?

**Comment by Genyok** [comment]
From the binance api documentation.

2023-06-28

Notice:

REST

The following endpoints will no longer be supported from 2023-07-15:
      GET /fapi/v1/account
      GET /fapi/v1/balance
      GET /fapi/v1/positionRisk
Please switch to corresponding v2 endpoints:
     GET /fapi/v2/account
     GET /fapi/v2/balance
     GET /fapi/v2/positionRisk

https://binance-docs.github.io/apidocs/futures/en/#change-log

**Comment by vunovikov** [comment]
Thanks, I've already made the necessary edits to manager.py

**Comment by maximborodin** [comment]
So when the new version with the fix will be released?

**Comment by Genyok** [comment]
Make the changes to manager.py yourself.
Here is the code I changed for myself.

Function _create_futures_api_uri  in manager.py.

`def _create_futures_api_uri(self, path):
        if path == 'balance':
            api_version = self.FUTURES_API_VERSION2
        elif path == 'account':
            api_version = self.FUTURES_API_VERSION2
        elif path == 'positionRisk':
            api_version = self.FUTURES_API_VERSION2
        else:
            api_version = self.FUTURES_API_VERSION
        return self.FUTURES_URL + '/' + api_version + '/' + path`

Function futures_exchange_info in manager.py

`def futures_exchange_info(self):
        """Current exchange trading rules and symbol information

        https://binance-docs.github.io/apidocs/futures/en/#exchange-information-market_data

        """
        return self._request_futures_api('get', 'exchangeInfo', throw_exception=False)`

**Comment by Genyok** [comment]
Make the changes yourself in manager.py.
Here are the changes that I made for myself.

Function_create_futures_api_uri in manager.py.
```python
def _create_futures_api_uri(self, path):
        if path == 'balance':
            api_version = self.FUTURES_API_VERSION2
        elif path == 'account':
            api_version = self.FUTURES_API_VERSION2
        elif path == 'positionRisk':
            api_version = self.FUTURES_API_VERSION2
        else:
            api_version = self.FUTURES_API_VERSION
        return self.FUTURES_URL + '/' + api_version + '/' + path
```
Function futures_exchange_info in manager.py
```python
def futures_exchange_info(self):
        """Current exchange trading rules and symbol information

        https://binance-docs.github.io/apidocs/futures/en/#exchange-information-market_data

        """
        return self._request_futures_api('get', 'exchangeInfo', throw_exception=False)
```

**Comment by vunovikov** [comment]
A new version of the library has appeared, but the necessary edits are still missing

**Comment by oliver-zehentleitner** [comment]
I am sorry that this has taken so long! I had to finance the project and implement the new licensing so that I could continue. From now on, updates like this will only take a few hours!
